# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f00ad6d718664176f25495924ba13934096d7dde8ad538d8b4b2ac8363cc0eebb3bd9599f818560b888dd8bf49e187018fb6ae7e463a62566979bdda8f10d8e

test:
  secret_key_base: 209e7c8fd4148df005d3ede42bd9beed205018b8f85b522c9d024f2567ceb0bacef840b6b98f1094bc90f193c1a0621009c270066b8e6e01a30c5b5ebff5b6a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
